SELECT * FROM
(
    SELECT A.CAR_ID ,A.CAR_TYPE ,ROUND((A.DAILY_FEE - (A.DAILY_FEE /100 * C.DISCOUNT_RATE)) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR  A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID 
                                                     AND B.START_DATE <= '20221130' 
                                                     AND B.END_DATE >='20221101'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  C ON A.CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '30일 이상'
    WHERE A.CAR_TYPE IN('SUV','세단')
    AND B.CAR_ID IS NULL
) A
WHERE A.FEE >=500000 AND A.FEE  <2000000
ORDER BY A.FEE DESC, A.CAR_TYPE ASC,A.CAR_ID DESC