SELECT a.MEMBER_ID, a.MEMBER_NAME, a.GENDER, DATE_FORMAT(a.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE a
WHERE DATE_FORMAT(a.DATE_OF_BIRTH, '%m') = '03'
AND a.TLNO is NOT NULL
AND a.GENDER = 'W'
ORDER BY a.MEMBER_ID